name: market
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  email_validator: '^2.1.16'
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  go_router: ^14.1.2
  mailer: ^6.1.0
  url_launcher: ^6.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env

